---
- name: Playbook Proxmox (Create)
  hosts: localhost
  gather_facts: no
  tasks:
  - name: include variable
    include_vars: var_{{ lokasi }}.yml

  - name: Variable untuk container di Setiap Lokasi
    set_fact:
       container: "pve_{{ lokasi }}"

  - name: Task untuk container
    include_tasks: container.yml
    with_items: "{{ groups[container] }}"
