- name: Get CSRF Token
  ansible.builtin.uri:
    url: "{{ proxmox_api_url }}/access/ticket"
    method: POST
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    validate_certs: no
    body_format: json
    body:
      username: "{{ api_user }}"
      password: "{{ api_password }}"
  register: csrf_token_result
  delegate_to: localhost

- name: Update Container Configuration
  ansible.builtin.uri:
    url: "{{ proxmox_api_url }}/nodes/{{ node }}/lxc/{{ container_item.vmid }}/config"
    method: PUT
    headers:
      Cookie: PVEAuthCookie={{ csrf_token_result.json.data.ticket }}
      CSRFPreventionToken: "{{ csrf_token_result.json.data.CSRFPreventionToken }}"
    validate_certs: no  # Disable SSL verification
    body_format: json
    body:
      memory: 1024  # Update memory to 1024 MB
      cores: 2      # Update CPU cores to 2
      swap: 1024
      rootfs: "local-lvm:vm-{{ container_item.vmid }}-disk-0,size=10G"
      description: "Updated container description"
  register: api_response
  delegate_to: localhost
  with_items: "{{ containers }}"
  loop_control:
    loop_var: container_item
